name: 'lint'

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '12.x'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: 'install main deps'
        run: npm ci

      - name: 'install'
        run: npm run deps

      - name: 'lint'
        run: npm run lint:all
