name: 'lint'

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: porostik/translation-check@master
        with:
          path_to_files: 'packages/shared/src/translations'
          main_file: 'main.json'

      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '16.x'

      # - name: 'deps'
      #   run: npx lerna bootstrap

      # - name: 'lint'
      #   run: npm run lint:all

      # - name: 'test'
      #   run: npm run test

      # - name: 'build'
      #   run: npm run build

      - name: Test
        uses: ./.github/actions/test
